version: '3.1'

services:
  db-tests:
    container_name: postgres-test
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: melifreshtest
    ports:
      - 5433:5432

  redis-tests:
    image: redis:3.2.5-alpine
    ports:
      - 6380:6379