version: '3.1'

services:
  db:
    container_name: postgres-test
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: melifreshtest
    ports:
      - 5433:5432