version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: melifresh
    ports:
      - 5432:5432

  redis:
      image: redis:3.2.5-alpine
      ports:
        6379:6379