name: ci-java

on:
  push:

jobs:
  container-job:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: melifreshtest
          POSTGRES_PASSWORD: docker
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:3.2.5-alpine
        ports:
          - 6380:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Google Java Formatter
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn -B test --file pom.xml